### ISSUE TITLE
No UEFI/boot output on the Intel NUC 9 Pro Kit NUC9VXQNX with mini PiKVM v4

### ISSUE THREAD

**Issue by medecigo3** [pikvm/pikvm#1275]
Hi developers, 

I'm unable to see video whilst the mini PiKVM v4 is connected to the HDMI port of my Intel NUC 9 Pro Kit NUC9VXQNX.

Can you please help debug this problem? Thanks in advance. 

Regards, 
Arturo.

**Comment by mdevaev** [comment]
Hello! Is this a latest version of PiKVM OS? If not, please update it: `curl https://files.pikvm.org/update-os.sh | bash`.

After that, use command `rw; kvmd-edidconf --restore-default=v4mini; reboot`

It should help because we fixed display EDID.

**Comment by medecigo3** [comment]
Hi @mdevaev , thanks for your help. 

Indeed I was missing the OS update. I can confirm my mini PiKVM v4 has working video, mouse and keyboard with my Intel NUC 9 Pro Kit NUC9VXQNX.

Regards, 
Arturo.

**Comment by mdevaev** [comment]
Glad to hear it. You're welcome!

**Comment by mdevaev** [comment]
Did you try `System -> Reset stream`?

**Comment by medecigo3** [comment]
@mdevaev , Thanks for the tip. 

I've now tried the `System -> Reset stream`  several times however the issue still persists, I see a screen with static noise. Screenshot attached. 
<img width="1526" alt="VideoScreenAfterStreamReset-14-03-2024" src="https://github.com/pikvm/pikvm/assets/36109246/174086dc-f2e1-489a-a05e-7a06c78ca29b">


Regards, 
Arturo.

**Comment by mdevaev** [comment]
Could you take a photo of your setup?

**Comment by medecigo3** [comment]
Please see my setup in the screenshots attached:
![IMG20240314155433](https://github.com/pikvm/pikvm/assets/36109246/04a6c0e5-6075-4d48-8383-bdf1abb71f35)
![IMG20240314155442](https://github.com/pikvm/pikvm/assets/36109246/18003c3e-b1f0-4fb0-93de-c0b3b948602e)
![IMG20240314155459](https://github.com/pikvm/pikvm/assets/36109246/43f7dd3c-5660-404a-942b-a3caa343672d)
![IMG20240314155525](https://github.com/pikvm/pikvm/assets/36109246/6c367fd1-af70-4ad7-a908-b64ca7f54a76)
![IMG20240314155543](https://github.com/pikvm/pikvm/assets/36109246/64181795-d4af-45ea-a39c-5d0ea5e7ad06)

**Comment by mdevaev** [comment]
Thank you. Looks fine for me. There is another recipe to fix the connection. Please check it:
1. Close the web page.
2. Wait ~15 seconds
3. `systemctl stop kvmd-tc358743`
4. Wait ~5 seconds
5. `systemctl start kvmd-tc358743`
6. Open the stream.

**Comment by medecigo3** [comment]
Unforntunately the last recipe fix did't solve the screen with static noise. 
Regards, 
Arturo.

**Comment by mdevaev** [comment]
Got it. Please wait a bit, we'll debug it on our side today.

**Comment by mdevaev** [comment]
What happens if you make `systemctl stop kvmd-tc358743` and after that open the stream?

**Comment by medecigo3** [comment]
Hi @mdevaev , 

I've tried with `systemctl stop kvmd-tc358743`. Afterwards, I tried close/open the web interface and/or `System -> Reset stream` but a the message < NO SIGNAL > appears on the screen. What are the steps to open the stream? 
Regards, 
Arturo.

**Comment by mdevaev** [comment]
After stopping, when you have `NO SIGNAL`, please run `v4l2-ctl --log-status` and save this log. Run `systemctl start kvmd-cc358743` while you have the `NO SIGNAL` stream, wait for the picture and run `v4l2-ctl --log-status` again. Describe what you see and attach both logs.

**Comment by medecigo3** [comment]
Please find the logs attaached after running `v4l2-ctl --log-status` while `no signal` message is  disaplyed on KVM web interface. 
[v4l2-ctl --log-status.log](https://github.com/pikvm/pikvm/files/14620549/v4l2-ctl.--log-status.log)

The `systemctl start kvmd-cc358743` command generated the following error  while `no signal` is displayed on the KVM web interface: 
`Failed to start kvmd-cc358743.service: Unit kvmd-cc358743.service not found.`

**Comment by mdevaev** [comment]
Typo. `systemctl start kvmd-tc358743`

**Comment by medecigo3** [comment]
@mdevaev , plese see the debugging steps below. 

1. Video is lost:
![1 0)WebInterfaceStaticNoise](https://github.com/pikvm/pikvm/assets/36109246/d335214a-ac87-4cd1-9954-b675239b1ce4)
2.  Close the web page.
4. Wait ~15 seconds
5. `systemctl stop kvmd-tc358743` See logs.txt
6. Wait ~5 seconds
7. Open Web page and start KVM session
8. NO SIGNAL 
9. `systemctl start kvmd-tc358743` See logs.txt
10. Result:
![Final](https://github.com/pikvm/pikvm/assets/36109246/c9af8bf4-71ea-4d09-88ff-57913aeaa2bf)

Logs: 
[logs.txt](https://github.com/pikvm/pikvm/files/14623317/logs.txt)

**Comment by mdevaev** [comment]
> Logs:
> [logs.txt](https://github.com/pikvm/pikvm/files/14623317/logs.txt)

Is this a log after all steps, when static noise is back?

**Comment by mdevaev** [comment]
Ah, no, I see, Please make log after the starting tc358743 too.

**Comment by medecigo3** [comment]
@mdevaev m please find the logs attached: 
[logs.txt](https://github.com/pikvm/pikvm/files/14646112/logs.txt)

Steps:
1. Video is lost:
![1 0)WebInterfaceStaticNoise](https://github.com/pikvm/pikvm/assets/36109246/d4cea844-f9a9-43d4-becf-e0ed2013f78c)
2. Close the web page.
3. Wait ~15 seconds
4. systemctl stop kvmd-tc358743
5. Wait ~5 seconds
6. Open Web page and start KVM session
7. NO SIGNAL
![7 0)NoSignal](https://github.com/pikvm/pikvm/assets/36109246/5730e8b8-6336-47f2-b11d-bff618c7a2ae)
8. v4l2-ctl --log-status
9. systemctl start kvmd-tc358743
10. v4l2-ctl --log-status

**Comment by mdevaev** [comment]
And after `systemctl start kvmd-tc358743` you see the noise again, right?

**Comment by medecigo3** [comment]
Correct, after `systemctl start kvmd-tc358743`  is executed, the static noise still appears in the video stream.

**Comment by mdevaev** [comment]
Got it. We'll check possible buggy places with this scenario.

**Comment by medecigo3** [comment]
Please find logs with a new test attached:

[log.txt](https://github.com/pikvm/pikvm/files/14722034/log.txt)

Steps to reproduce the issue:

1. Video is lost. 
2. Close the web page.
3. Wait ~15 seconds
4. `systemctl stop kvmd-tc358743`
5. Wait ~5 seconds
6. Open Web page and start KVM session
7. NO SIGNAL screen appears
8. `v4l2-ctl --log-status`
9. `systemctl start kvmd-tc358743`
10. `v4l2-ctl --log-status`
11. Wait ~5 mins.
12. Video stream not restored:
![12 0)StaticNoise](https://github.com/pikvm/pikvm/assets/36109246/a54b99d9-8784-4adb-a3ad-b5574dfcab6d)

**Comment by mdevaev** [comment]
Can you try different HDMI cable?

**Comment by medecigo3** [comment]
Hi @mdevaev , what are the HDMI cable specs that you would recommend ?

**Comment by mdevaev** [comment]
Just try different cables that you have at home. There is no need to buy anything, at least for the test.

**Comment by medecigo3** [comment]
Hi @mdevaev , I've tried with different cables however I'm facing the same issue. The quickest solution seems to be to disconnect and re-connect the HDMI cable. 

Regards, 
Arturo.

**Comment by medecigo3** [comment]
Hello @mdevaev , can you please confirm what's the expected behavour with other devices? After a moment of inactivity, should the PiKVM automatically establish the video or should this trigger a manual action to re-establish the video stream?
Regards, 
Arturo.

**Comment by mdevaev** [comment]
This is not expected behavour. And it's not reproducible on our test hosts. We'll checking soft/hardware now.

**Comment by medecigo3** [comment]
@mdevaev , can we compare our logs when video stream is re-established after a period of inactivity? In case the HDMI stream isn't restablished correctly, should we expect to see errors in the logs? Is there a communicaiton protocol with error handling mechanism for streaming video content? 
Regards, 
Arturo.

**Comment by mdevaev** [comment]
It seems to be a hardware incompatibility with your particular NUC model :/ I haven't figured out how to reproduce this on my side yet.

**Comment by medecigo3** [comment]
Hi @mdevaev , it would be difficult to reproduce the issue on your side. What would be the best practices in this situation? 

- HDMI cable specifications? 
- Close the web page imediately when not in use? 
- script to restart the PIKVM? 

My NUC also features graphics card NVIDIA Quadro P2200 special NUC9 version which supports 4 x DisplayPorts. the NUC ins't running with this card. How well would the PIKVM support video if using a DP -> HDMI adapter connected to the PIKVM ?  

Regards, 
Arturo.

**Comment by mdevaev** [comment]
I only have a couple of reports about a similar problem, so I don't really understand what's going on here. Judging by the logs and indirect debugging results, the problem is that NUC does not strictly follow the HDMI specifications in terms of connection management. Right now I can't do anything about it, just advise not to turn off the screen and not use various energy-saving modes. Sorry.
