### ISSUE TITLE
webGUI target window oversized by just a few pixel

### ISSUE THREAD

**Issue by VoeGalore** [pikvm/pikvm#599]
I have PiKVM v3 Kickstarter version and upgraded to the latest (as of 2022-01-08), but this issue is present in my previous v2 build from early last year.

The webGUI target video feed is automatically resized to target resolution, you may also use the "." button in the top right corner of the video feed window to manually resize it back to target resolution (if target resolution is smaller than the screen you are viewing it with).
However the video feed has always been non-pixel-perfect. Noticeably there are blurry areas indicating the displaying resolution not completely matching the target(video feed) resolution. For example: my target resolution is 1280x720, and the video feed I got is 1282x722, the 2px discrepancy caused blurriness.
If I manually adjust the window, I might get it to display pixel-perfectly again, and it is showing as 1280x720 size.

The screenshots I took are from a 2560x1440 monitor (height truncated to exclude window title and Windows 10 taskbar), it shows what it would look like when pixel-perfect AND when default resized (or with "." button). I attached a full-screen green color to help identify screen size given the video feed window generates an 1px edge already.

The issue is present with either MJPEG or H264 compression of the video feed, and when pixel-perfection is achieved, you could clearly tell the difference of blurriness and compression artefacts. The blurriness is not a compression artefact.
The issue is present with different browsers. I tried Chrome & Firefox.
The issue is NOT present when using the video feed full screen on a matching resolution display. e.g. showing 1920x1080 target feed full-screen on a 1080p display, or showing 1280x720 target feed full-screen on a 720p display. Meaning it's likely a window-scaling related issue that can be tuned in the webGUI software,
The issue is NOT present when using VNC client. Using TigerVNC, when display is set to 1:1 scaling, it shows pixel-perfect video feed even if it does not achieve full screen.

**How to recreate the bug**
scaling factor 1 (100% scaling in MS Windows), use the webGUI and open a target feed with target resolution smaller than the browser window you are viewing it with. e.g. viewing 720p target with a 1080p monitor, or viewing 1280x1024 target with 1440p monitor.

**Expected behavior**
Pixel-perfect video feed when default/resized, if viewing space allows.

**Screenshots**
1&2 720p feed manually adjusted to pixel-perfection [expected behavior]. full screen green display showing real feed size (you can count the pixel or parse it in image editing software)
![微信截图_20220108142704](https://user-images.githubusercontent.com/66440393/148659613-263733f0-77e7-4757-b8f2-46c758568714.png)
the green size is exactly 1280x720
![微信截图_20220108142736](https://user-images.githubusercontent.com/66440393/148659614-c43eae67-e04e-46dd-af14-f72e1088d186.png)

3&4 Same as 1&2 BUT focus is lost
![微信截图_20220108142746](https://user-images.githubusercontent.com/66440393/148659617-42b89072-6421-4c00-8dbb-e0240b07c239.png)
![微信截图_20220108142756](https://user-images.githubusercontent.com/66440393/148659618-fdf097c8-dc24-4806-8c01-11da84c50f7c.png)

5&6 Default centered window size (or after hitting "." button to manually center&resize). Also showing full green screen for easy size comparison.
![微信截图_20220108142815](https://user-images.githubusercontent.com/66440393/148659621-c1661d53-a38e-47fd-afdd-4e47b8896f98.png)
the green size is 1282x722
![微信截图_20220108142828](https://user-images.githubusercontent.com/66440393/148659622-cc07aac2-2828-41e0-ab29-52a795dc0d45.png)

7&8 Same as 5&6 BUT focus is lost
![微信截图_20220108142836](https://user-images.githubusercontent.com/66440393/148659628-220cbe48-79e1-4e27-8ca1-265a0244d060.png)
![微信截图_20220108142845](https://user-images.githubusercontent.com/66440393/148659629-8f581e81-c2f9-4cf1-b1b2-4e455c42ebfc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 (19043.1415)
 - Browser: Chrome_v97 (and Firefox)
 - VNC client: TigerVNC

**PiKVM info:**
  - Raspberry Pi board version: Pi 4 model B rev 1.4
  - PiKVM platform: v3 HAT (Kickstarter kit w/ steel case)
  - Video capture type:  CSI bridge
  - KVMD version: 3.52-1
  - uStreamer version: 4.11-1
  - Linux kernel: 5.10.52-14-ARCH

**Comment by mdevaev** [comment]
Presumbly it's fixed in the new KVMD release 3.64. Could you confirm?

**Comment by VoeGalore** [comment]
I can confirm one thing: when I focus/defocus the streaming window within the webGUI, the streaming window does not change size anymore, this is surely welcomed.

The extra pixel on window width is still present, please see attached screenshots (taskbar hidden, URL redacted):

default resizing with "." button
![image](https://user-images.githubusercontent.com/66440393/159409509-bbc01a00-45c0-4d05-aaba-49c03a9658f9.png)

manually decrease width by **1px** (used to be 2px?)
![image](https://user-images.githubusercontent.com/66440393/159409672-b092e51d-f9e8-4579-993e-a4fb8d6d103f.png)

**Comment by VoeGalore** [comment]
Here are 2 additional screenshots taken with default stream window size (not pixel-perfect) and manually adjusted stream window size (pixel perfect). With the help of an additional screenshot tool you can see it's just 2 pixels wider than it needs to be to achieve pixel-perfect scaling.

![InkedScreenshot 2022-04-26 142250_LI](https://user-images.githubusercontent.com/66440393/165377400-03a3864d-70f2-47c5-bd67-e64570e80dde.jpg)

![InkedScreenshot 2022-04-26 142446_LI](https://user-images.githubusercontent.com/66440393/165377401-16ac02a2-4f60-49e2-963a-382e69d8812e.jpg)

**Comment by VoeGalore** [comment]
Please check [https://github.com/pikvm/kvmd/pull/86](url) for potential fix of this issue, and [https://github.com/pikvm/kvmd/pull/87](url) for another minor fix of visual.
